// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_F5vmsv-cmFsK9MDicEm12QqpDS95eQ',
    appId: '1:147298740710:android:efd7b0d08fa551027b8e27',
    messagingSenderId: '147298740710',
    projectId: 'mybudegtpro',
    storageBucket: 'mybudegtpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXXC6M3YSGXlnZ0JxZXIcKmSc-CREPic',
    appId: '1:147298740710:ios:72924cbdc8043d067b8e27',
    messagingSenderId: '147298740710',
    projectId: 'mybudegtpro',
    storageBucket: 'mybudegtpro.firebasestorage.app',
    iosClientId: '147298740710-7v4al3sdq8jvlotk473teqbt15vt9tsf.apps.googleusercontent.com',
    iosBundleId: 'com.plustudios.myBudgetPro',
  );
}
