/**
 * Financial Statement & Export Generator — OrbitLife Personal CFO
 * Generates monthly financial statements and transaction exports.
 */

/**
 * Generate a Monthly Financial Statement Report
 * 
 * @param {Object} userData Complete user profile from Firestore
 * @param {string} [monthStr=null] "YYYY-MM" (defaults to current month)
 * @returns {Object} Statement summary and formatted text document
 */
function generateMonthlyStatement(userData, monthStr = null) {
  if (!userData) return null;

  const targetMonth = monthStr || new Date().toISOString().substring(0, 7); // e.g. "2026-08"
  const expenses = (userData.expenses || []).filter((e) => e.date && e.date.startsWith(targetMonth));
  const incomes = (userData.incomes || []).filter((i) => i.date && i.date.startsWith(targetMonth));
  const transactions = (userData.transactions || []).filter((t) => t.date && t.date.startsWith(targetMonth));

  const totalSpent = expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);
  const totalEarned = incomes.reduce((sum, i) => sum + (Number(i.amount) || 0), 0);
  const netSurplus = totalEarned - totalSpent;
  const savingsRate = totalEarned > 0 ? Math.round((netSurplus / totalEarned) * 100) : 0;

  // Category breakdown
  const categoryMap = {};
  expenses.forEach((e) => {
    const cat = e.categoryId || "General";
    categoryMap[cat] = (categoryMap[cat] || 0) + (Number(e.amount) || 0);
  });

  let reportText = `=================================================\n`;
  reportText += `       ORBITLIFE MONTHLY FINANCIAL STATEMENT      \n`;
  reportText += `       Period: ${targetMonth}                    \n`;
  reportText += `=================================================\n\n`;

  reportText += `1. FINANCIAL SUMMARY\n`;
  reportText += `-------------------------------------------------\n`;
  reportText += `Total Income / Earned:     Rs. ${totalEarned.toLocaleString("en-IN", { minimumFractionDigits: 2 })}\n`;
  reportText += `Total Expenses / Outflows: Rs. ${totalSpent.toLocaleString("en-IN", { minimumFractionDigits: 2 })}\n`;
  reportText += `Net Surplus / Savings:     Rs. ${netSurplus.toLocaleString("en-IN", { minimumFractionDigits: 2 })}\n`;
  reportText += `Monthly Savings Rate:      ${savingsRate}%\n\n`;

  reportText += `2. SPENDING BY CATEGORY\n`;
  reportText += `-------------------------------------------------\n`;
  for (const cat in categoryMap) {
    const amt = categoryMap[cat];
    const pct = totalSpent > 0 ? Math.round((amt / totalSpent) * 100) : 0;
    reportText += `• ${cat.padEnd(24)} Rs. ${amt.toLocaleString("en-IN").padEnd(10)} (${pct}%)\n`;
  }
  reportText += `\n`;

  reportText += `3. TRANSACTION LEDGER (${expenses.length + incomes.length} entries)\n`;
  reportText += `-------------------------------------------------\n`;
  reportText += `Date        Type     Amount (Rs)   Description / Merchant\n`;
  reportText += `-------------------------------------------------\n`;

  const allItems = [
    ...expenses.map((e) => ({ ...e, recordType: "EXPENSE" })),
    ...incomes.map((i) => ({ ...i, recordType: "INCOME" })),
  ].sort((a, b) => new Date(a.date) - new Date(b.date));

  allItems.forEach((it) => {
    const d = it.date ? it.date.substring(0, 10) : "----------";
    const t = it.recordType === "INCOME" ? "+INC " : "-EXP ";
    const amt = Number(it.amount || 0).toFixed(2).padStart(11);
    const desc = (it.description || it.source || it.title || "Transaction").substring(0, 24);
    reportText += `${d}  ${t}  ${amt}   ${desc}\n`;
  });

  reportText += `\n=================================================\n`;
  reportText += `Generated by OrbitLife AI Personal CFO Assistant\n`;
  reportText += `=================================================\n`;

  return {
    period: targetMonth,
    totalEarned,
    totalSpent,
    netSurplus,
    savingsRate,
    categoryBreakdown: categoryMap,
    reportText,
  };
}

module.exports = {
  generateMonthlyStatement,
};
